### ISSUE TITLE
Read SQlite connection string from app.config

### ISSUE THREAD

**Issue by ralfw** [ralfw/todoapp#1]
The app should read the SQlite connection string from a app.config/web.config appsettings entry.

**Comment by CannyDoersolutions** [comment]
you need to add Full path in web.config then and then i can able to read this right now i have added in App_Data folder so where ever you move this Site no matters to change it it wil automaticall pick from that Folder

**Comment by ralfw** [comment]
ok. so here's what you should do: read the connection string from the app.config. any file path is fine.
but: if you find a ~ in the path, then you replace it with the current server path.

if app.config contains

```
dbpath="~\App_data\tolist.db"
```

then you convert it internally to

```
c:\...whatever...\App_data\tolist.db
```

to replace ~ you call _HttpContext.Current.Server.MapPath(".")_

**Comment by CannyDoersolutions** [comment]
excatly

**Comment by CannyDoersolutions** [comment]
right now i have make on Form level dynamic code
see in TodoList.aspx.cs file 
 this.DBConnectionString = "Data source=" + HttpContext.Current.Server.MapPath("App_Data\ToDoTask.db") + ";Version=3;New=False;Compress=True;";

**Comment by ralfw** [comment]
i know. and that could stay almost the same. just load "~App_Data\ToDoTask.db" from a config setting. and replace ~ with Server.MapPath(".").

**Comment by ralfw** [comment]
It's ok you're using {RootPath} as a placeholder instead of ~.
