### ISSUE TITLE
Archive active task

### ISSUE THREAD

**Issue by ralfw** [ralfw/todoapp#6]
An active task (one that is not archived) displayed in the current task list can be switched to archived.
It then vanishes from the currently displayed list. But it will be shown again, when the "show archived" flag is set.

An archived task cannot be un-archived (made active again).

Budget: 1 hour

**Comment by CannyDoersolutions** [comment]
You want this functionality from displayed Grid Task page itself right ?

**Comment by ralfw** [comment]
If you mean by "displayed grid task page" the page where there are two tables (our currently only page), then yes. Archiving should be done in the data table on the right side.

**Comment by CannyDoersolutions** [comment]
ok once the task is archieved than should it be editable for other thingd likr title and description and all  or not ?

**Comment by ralfw** [comment]
good question. once a task has been archived it should not be editable anymore. but you can still open its detail view page.

**Comment by ralfw** [comment]
Nice idead to show a messagebox to confirm archivation.
