### ISSUE TITLE
User login

### ISSUE THREAD

**Issue by ralfw** [ralfw/todoapp#9]
A user should be able to login.
1. User logs in with his email-address.
2. While logged in he is automatically assigned to new tasks as their owner. The owner cannot be changed later on.
3. If no user is logged in, no changes can be made to tasks/lists.
4. A user stays logged in across sessions until explictly logged out.

<img width="886" alt="bildschirmfoto 2015-07-12 um 14 43 26" src="https://cloud.githubusercontent.com/assets/132662/8637805/6c09223c-28a4-11e5-9a89-df72c2b59862.png">

Also see the requirements doc for a description of this.

Budget: 2 hours

**Comment by CannyDoersolutions** [comment]
Done

**Comment by ralfw** [comment]
I cannot use the app without loggin in. That's not what was meant by
1. If no user is logged in, no changes can be made to tasks/lists.

Also, if you look at the requirements document, you'll find the login part at the top of the homepage with the tables below. Currently it's isolated on it's own page.

![2015-07-13_13-28-45](https://cloud.githubusercontent.com/assets/132662/8648717/43656240-2963-11e5-9800-5e33bc6a0160.png)

Drawing it in an isolated way (as also can be found in the req. doc) was just a way to focus on the login-process.

**Comment by ralfw** [comment]
After I entered a login-name and pressed "login" this error occurred:

<img width="1036" alt="bildschirmfoto 2015-07-13 um 13 33 34" src="https://cloud.githubusercontent.com/assets/132662/8648776/e1d73b38-2963-11e5-9592-c0c2163c0b62.png">

**Comment by CannyDoersolutions** [comment]
git clone https://canny31032015@bitbucket.org/canny31032015/ccdschool.git

Hi i have Created Git repository on Bitbucket can u try to configure this ?

Please let me know

**Comment by CannyDoersolutions** [comment]
Also done this changes

**Comment by CannyDoersolutions** [comment]
also updated source on dropbox as well
